version: "3.9"

services:
  web:
    build: .
    container_name: biblionet_v3_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "biblio1"
      DEBUG: "True"
      DB_NAME: "biblionet"
      DB_USER: "biblio"
      DB_PASSWORD: "Proyecto1"
      DB_HOST: "db"
      DB_PORT: "3306"
      TIME_ZONE: "America/Tegucigalpa"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: biblionet_v3_db
    restart: always
    environment:
      MYSQL_DATABASE: "biblionet"
      MYSQL_USER: "biblio"
      MYSQL_PASSWORD: "Proyecto1"
      MYSQL_ROOT_PASSWORD: "rootpass"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: biblionet_v3_pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: "biblio"
      PMA_PASSWORD: "Proyecto1"
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
